club_index:
    path:     /
    defaults: { _controller: "clubsBundle:Club:index" }
    methods:  GET

club_show:
    path:     /{idClub}/show
    defaults: { _controller: "clubsBundle:Club:show" }
    methods:  GET

club_new:
    path:     /new
    defaults: { _controller: "clubsBundle:Club:new" }
    methods:  [GET, POST]

club_edit:
    path:     /{idClub}/edit
    defaults: { _controller: "clubsBundle:Club:edit" }
    methods:  [GET, POST]

club_delete:
    path:     /{idClub}/delete
    defaults: { _controller: "clubsBundle:Club:delete" }
    methods:  DELETE
