services:
#    clubs.example:
#        class: clubsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    clubs.admin.club:
        class: clubsBundle\Admin\ClubAdmin
        arguments: [~, clubsBundle\Entity\Club, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Club }
        public: true

    clubs.admin.workshops:
        class: clubsBundle\Admin\WorkshopsAdmin
        arguments: [~, clubsBundle\Entity\Workshops, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Workshops }
        public: true
